WebApp/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models.Interfaces;

namespace WebApp.Models
{
    public class Product : IUserDateStamp
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Characteristic { get; set; }
        public int GroupId { get; set; }
        public int UnitId { get; set; }

        public Group Group { get; set; }
        public MeasurementUnit Unit { get; set; }

        public int DetailedInfoId { get; set; }
        public DetailedInfo DetailedInfo { get; set; }

        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
        public DateTimeOffset CreatedDate { get; set; }
        public DateTimeOffset UpdatedDate { get; set; }
        [ForeignKey("CreatedBy")]
        public User CreatedUser { get; set; }
        [ForeignKey("UpdatedBy")]
        public User UpdatedUser { get; set; }
    }
}

WebApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class ProductController : Controller
    {

        private readonly WarehouseContext _context;

        public ProductController(WarehouseContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var grups = await _context.Groups.ToListAsync();
            return View(grups);
        }
        
        [HttpGet]
        public async Task<IActionResult> ViewProducts(int id)
        {
            var products = await _context.Products.Where(p => p.GroupId == id).ToListAsync();
            return View(products);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var productDetailsViewModel = await _context.Products.Where(p => p.Id == id)
                .Select(p => new ProductDetailsViewModel
                {
                    AdditionalCharacteristics = p.DetailedInfo.AdditionalCharacteristics,
                    Characteristic = p.Characteristic,
                    Description = p.DetailedInfo.Description,
                    GroupId = p.GroupId,
                    Groupname = p.Group.Name,
                    MainImagePath = p.DetailedInfo.MainImagePath,
                    Productcode = p.Code,
                    ProductId = p.Id,
                    Productname = p.Name,
                    Paths = p.DetailedInfo.ImagePaths.Select(im => im.Path).ToList()
                })
                .FirstOrDefaultAsync();

            return View(productDetailsViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
    }
}

WebApp/Views/Product/Create.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Create</title>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
</head>
<body>
   


</body>
</html>

WebApp/Views/Product/Details.cshtml
@model ProductDetailsViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <h1>@Model.Productname</h1>
    <h3>@Model.Groupname</h3>
    <h3>@Model.Productcode</h3>
    <div>
        <img src="@Model.MainImagePath" />
        <ul>
            @foreach (var path in Model.Paths)
            {
                <li>
                    <img src="@path" />
                </li>
            }

        </ul>
    </div>
    <p>@Model.Description</p>
    <p>@Model.Characteristic</p>
    <p>@Model.AdditionalCharacteristics</p>
    @*реализовать отображение сходныех с этим продуктом (с помощью  @Model.GroupId) *@
</body>
</html>

WebApp/Views/Product/Index.cshtml
@model List<Group>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <ul>
        @{ foreach (var group in Model)
            {
                <li>
                    <a asp-controller="Product" asp-action="ViewProducts" asp-route-id="@group.Id">@group.Name</a>
                </li>
            }
        }
    </ul>
</body>
</html>

WebApp/Views/Product/ViewProducts.cshtml
@model List<Product>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewProducts</title>
</head>
<body>
    <ul>
        @foreach (var product in Model)
        {
        <li>
            <a asp-controller="Product" asp-action="Details" asp-route-id="@product.Id">@product.Name</a>
        </li>
        }
    </ul>
</body>
</html>